# -*- coding: utf-8 -*-
"""ML_MAU_PAGADOR

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XsM6YN99hvNVrJO6OlCG1N0KpHorgCab

# Módulo 07 - Tarefa 02

#### 1) Carregue a base e garanta que a base está como deveria.

Considere a base que você ajustou na lição passada. Carregue-a. Caso ainda haja alguma pendência, ajuste - lembre-se de que o scikitlearn não recebe variáveis em formato string, somente numéricas, e não aceita '*missings*'.

- Separe 70% da base para treinamento e 30% para validação. Cada uma dessas partes terá dois objetos, um armazenando a variável resposta ```mau```e outro armazenando as variáveis explicativas (lembrando: sem variáveis string, já com as dummies).
"""

import pandas as pd

# Ler a base
df_modelo = pd.read_csv('df_modelo.csv')

# Tratar valores nulos
df_modelo['OCCUPATION_TYPE'] = df_modelo['OCCUPATION_TYPE'].fillna('Sem informacao')

# Variáveis categóricas que precisam virar dummy
variaveis_dummy = [
    'CODE_GENDER',
    'FLAG_OWN_CAR',
    'FLAG_OWN_REALTY',
    'NAME_INCOME_TYPE',
    'NAME_EDUCATION_TYPE',
    'NAME_FAMILY_STATUS',
    'NAME_HOUSING_TYPE',
    'OCCUPATION_TYPE'
]

# Criar dummies
df_modelo_dummies = pd.get_dummies(
    df_modelo,
    columns=variaveis_dummy,
    drop_first=True,
    dtype=int
)

# Colunas numéricas originais que queremos usar no modelo
colunas_numericas_modelo = [
    'CNT_CHILDREN',
    'AMT_INCOME_TOTAL',
    'DAYS_BIRTH',
    'DAYS_EMPLOYED',
    'FLAG_MOBIL',
    'FLAG_WORK_PHONE',
    'FLAG_PHONE',
    'FLAG_EMAIL',
    'CNT_FAM_MEMBERS'
]

# Identificar automaticamente as colunas dummy criadas
colunas_dummies_modelo = [
    coluna for coluna in df_modelo_dummies.columns
    if any(coluna.startswith(var + '_') for var in variaveis_dummy)
]

# Criar base final para o modelo
df_colunas_modelo = df_modelo_dummies[
    colunas_numericas_modelo + colunas_dummies_modelo + ['mau']
].copy()

"""#### 2) Vamos para o modelo:

1. Defina um objeto com a função da árvore de decisão vista em aula.
2. Treine o modelo com os dados que você separou para treinamento.
3. Visualize a árvore. Talvez você queira aumentar um pouco a figura.
4. Produza uma visualização da matriz de classificação (ou matriz de confusão) - coloque os rótulos como "aprovados" e "reprovados" - pois afinal de contas, são essas as decisões que se podem tomar com propostas de crédito.
5. Calcule a acurácia na base de treinamento
"""

# Separar variáveis de entrada e resposta
X = df_colunas_modelo.drop(columns=['mau'])
y = df_colunas_modelo['mau']

ccp_alphas_validos = ccp_alphas[ccp_alphas >= 0]

ccp_alphas_validos = ccp_alphas_validos[:-1]

melhor_alpha = df_resultados_alpha.sort_values(
    by='f1_1',
    ascending=False
).iloc[0]['ccp_alpha']

melhor_alpha

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

melhor_alpha = 1.9591914612592648e-05

arvore_final = DecisionTreeClassifier(
    class_weight='balanced',
    random_state=42,
    ccp_alpha=melhor_alpha
)

arvore_final.fit(X_train, y_train)

y_pred_final = arvore_final.predict(X_test)

import matplotlib.pyplot as plt
from sklearn.tree import plot_tree

plt.figure(figsize=(30, 15))

plot_tree(
    arvore_final,
    feature_names=X.columns,
    class_names=['Aprovado', 'Reprovado'],
    filled=True,
    rounded=True,
    fontsize=9,
    max_depth=3
)

plt.title('Árvore de Decisão - Primeiros Níveis')
plt.show()

import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

# Gerar matriz de confusão
cm = confusion_matrix(y_test, y_pred_final)

# Criar visualização
disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=['Aprovados', 'Reprovados']
)

disp.plot(cmap='Blues', values_format='d')
plt.title('Matriz de Confusão - Decisão de Crédito')
plt.xlabel('Classe predita')
plt.ylabel('Classe real')
plt.show()

from sklearn.metrics import accuracy_score

# Predição na base de treino
y_pred_train_nova = arvore_nova.predict(X_train)

# Predição na base de teste
y_pred_test_nova = arvore_nova.predict(X_test)

# Acurácia
acuracia_train_nova = accuracy_score(y_train, y_pred_train_nova)
acuracia_test_nova = accuracy_score(y_test, y_pred_test_nova)

print(f"\nAcurácia na base de treinamento: {acuracia_train_nova:.2%}")
print(f"Acurácia na base de teste: {acuracia_test_nova:.2%}")



"""#### 3) Vamos avaliar o modelo na base de testes

1. Classifique a base de teste de acordo com a árvore que você treinou no item 2.
2. Produza a visualização da matriz de confusão para a base de teste.
3. Calcule a acurácia da base de teste. Compare com a acurácia da base de treinamento.
4. Treine uma nova árvore com número mínimo de observações por folha de 5 e máximo de profundidade de 10. Use o random_state = 123. Avalie a matriz de classificação. Observe a distribuição da predição - qual a proporção de proponentes foram classificados como 'maus'?
5. Como ficaria a acurácia se você classificasse todos os contratos como 'bons'?
"""

# Classificar a base de teste
y_pred_final = arvore_final.predict(X_test)

# Visualizar as primeiras classificações
y_pred_final[:10]

import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

# Matriz de confusão da base de teste
cm = confusion_matrix(y_test, y_pred_final)

# Visualização
fig, ax = plt.subplots(figsize=(6, 5))

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=['Aprovados', 'Reprovados']
)

disp.plot(ax=ax, cmap='Blues', values_format='d', colorbar=False)

plt.title('Matriz de Confusão - Base de Teste')
plt.xlabel('Classe predita')
plt.ylabel('Classe real')
plt.show()

from sklearn.metrics import accuracy_score

# Previsão na base de treinamento
y_pred_train = arvore_final.predict(X_train)

acuracia_train = accuracy_score(y_train, y_pred_train)

print(f"\nAcurácia na base de treinamento: {acuracia_train_nova:.2%}")
print(f"Acurácia na base de teste: {acuracia_test_nova:.2%}")

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import pandas as pd

# Criar nova árvore
arvore_nova = DecisionTreeClassifier(
    min_samples_leaf=5,
    max_depth=10,
    random_state=123
)

# Treinar com a base de treino
arvore_nova.fit(X_train, y_train)

# Classificar a base de teste
y_pred_nova = arvore_nova.predict(X_test)

import matplotlib.pyplot as plt
from sklearn.metrics import ConfusionMatrixDisplay

# Visualizar matriz de confusão da nova árvore
fig, ax = plt.subplots(figsize=(6, 5))

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm_nova,
    display_labels=['Aprovados', 'Reprovados']
)

disp.plot(
    ax=ax,
    cmap='Blues',
    values_format='d',
    colorbar=False
)

plt.title('Matriz de Confusão - Nova Árvore')
plt.xlabel('Classe predita pelo modelo')
plt.ylabel('Classe real')
plt.show()

proporcao_maus_preditos = (y_pred_nova == 1).mean() * 100

print(f"Proporção de proponentes classificados como maus: {proporcao_maus_preditos:.2f}%")

acuracia_todos_bons = (y_test == 0).mean()

print(f"Acurácia classificando todos como bons: {acuracia_todos_bons:.4f}")
print(f"Acurácia classificando todos como bons: {acuracia_todos_bons:.2%}")

"""Isso mostra por que a acurácia sozinha é perigosa nesse problema: um modelo “burro”, que aprova todo mundo, teria acurácia maior que alguns modelos treinados, mas não identificaria nenhum mau pagador."""

